Repository cms-patatrack/pixeltrack-standalone, pull requests merged in 2020-12, with the labels that each got.

#140 [general] Add support in Makefile for MAXWELL_50 ARCH
  Makefile
Labels: general

#141 [alpakatest] Add cudatest tests to alpakatest tests
  src/alpakatest/AlpakaCore/alpakaConfig.h
  src/alpakatest/plugin-Test1/alpaka/alpakaAlgo1.cc
  src/alpakatest/plugin-Test2/alpaka/alpakaAlgo2.cc
Labels: alpaka

#139 [kokkos] Use HintLightWeight in all Kokkos parallel operations
  src/kokkos/KokkosCore/HistoContainer.h
  src/kokkos/KokkosCore/hintLightWeight.h
  src/kokkos/plugin-PixelTriplets/kokkos/BrokenLineFitOnGPU.cc
  src/kokkos/plugin-PixelTriplets/kokkos/CAHitNtupletGeneratorKernels.cc
  src/kokkos/plugin-PixelTriplets/kokkos/RiemannFitOnGPU.cc
  src/kokkos/plugin-PixelVertexFinding/kokkos/gpuClusterTracksByDensity.h
  src/kokkos/plugin-PixelVertexFinding/kokkos/gpuClusterTracksDBSCAN.h
  src/kokkos/plugin-PixelVertexFinding/kokkos/gpuClusterTracksIterative.h
  src/kokkos/plugin-PixelVertexFinding/kokkos/gpuSortByPt2.h
  src/kokkos/plugin-PixelVertexFinding/kokkos/gpuVertexFinder.cc
  src/kokkos/plugin-SiPixelClusterizer/kokkos/SiPixelRawToClusterGPUKernel.cc
  src/kokkos/plugin-SiPixelClusterizer/kokkos/gpuClusterChargeCut.h
  src/kokkos/plugin-SiPixelClusterizer/kokkos/gpuClustering.h
  src/kokkos/plugin-SiPixelRecHits/kokkos/PixelRecHits.cc
Labels: kokkos

#145 Add warmup option to run the command once before starting the profiling
  run-scan.py
Labels: general

#148 Use the correct version of Eigen
  Makefile
Labels: general

#149 [kokkos] Update Kokkos to 3.3
  Makefile
Labels: kokkos

#150 [cudauvm] Fix table of compile macros
  README.md
Labels: cuda, documentation, unified memory
