Repository cms-patatrack/pixeltrack-standalone, pull requests merged in 2021-08, with the labels that each got.

#202 Fix uploading EventSetup conditions from multiple CUDA streams
  src/cuda/CUDACore/ESProduct.h
  src/cudacompat/CUDACore/ESProduct.h
  src/cudadev/CUDACore/ESProduct.h
  src/cudauvm/CUDACore/ESProduct.h
  src/hip/CUDACore/ESProduct.h
Labels: bug, cuda, cudacompat

#209 [all] Fix radix sort test
  src/cuda/test/radixSort_t.cu
  src/cudacompat/test/radixSort_t.cu
  src/cudadev/test/radixSort_t.cu
  src/cudauvm/test/radixSort_t.cu
  src/hip/test/radixSort_t.cu
Labels: cuda, hip

#210 Workarounds for the HIP port
  src/hip/CUDACore/radixSort.h
Labels: hip

#208 [all] Update Eigen and extend CUDA support
  Makefile
Labels: general, cuda

#213 Enable hwloc by default for Kokkos Threads
  Makefile
  README.md
Labels: kokkos

#214 Update run-scan.py
  run-scan.py
Labels: general

#215 Update Kokkos to 3.4.01
  Makefile
  README.md
Labels: kokkos
